package com.imdemo.im.domain;

public enum AuditEventType {
    LOGIN, LOGIN_FAILED, LOGOUT, PASSWORD_CHANGED,
    SHIFT_STARTED, SHIFT_FINISHED,
    ITEM_STARTED, ITEM_DONE, ITEM_PROBLEM, ITEM_SKIPPED, ITEM_REOPENED,
    PHOTO_UPLOADED, PHOTO_DELETED,
    FLAG_RAISED,
    FLAG_CONFIRMED, FLAG_DISMISSED, ITEM_APPROVED, ITEM_REJECTED,
    USER_CREATED, USER_UPDATED, USER_DELETED, USER_PASSWORD_RESET,
    CATALOG_CHANGED
}