-- Сроки хранения (вторичные), Версия 14 от 20.08.2026. Видны всем ролям; править могут SUPER_ADMIN и DIRECTOR.
create table shelf_life_doc (
    id        smallint primary key check (id = 1),
    title     varchar(200) not null,
    version   integer not null,
    doc_date  date,
    notice    varchar(500)
);
create table shelf_life_zone (
    code       varchar(10) primary key,
    label      varchar(60) not null,
    temp_text  varchar(30) not null,
    sort_order integer not null
);
create table shelf_life_section (
    id         bigserial primary key,
    title      varchar(100) not null,
    note       varchar(500),
    sort_order integer not null
);
create table shelf_life_product (
    id         bigserial primary key,
    section_id bigint not null references shelf_life_section(id) on delete cascade,
    name       varchar(200) not null,
    note       varchar(500),
    sort_order integer not null,
    active     boolean not null default true
);
create table shelf_life_rule (
    id           bigserial primary key,
    product_id   bigint not null references shelf_life_product(id) on delete cascade,
    kind         varchar(10) not null default 'SHELF' check (kind in ('SHELF','THAW','HOLD','WASH','DRY')),
    place        varchar(500) not null,
    term_text    varchar(200) not null,
    duration_min integer,
    zone         varchar(10) references shelf_life_zone(code),
    sort_order   integer not null
);
create index ix_shelf_product_section on shelf_life_product(section_id, sort_order);
create index ix_shelf_rule_product on shelf_life_rule(product_id, sort_order);

insert into shelf_life_doc(id, title, version, doc_date, notice) values
 (1, 'Таблица вторичных сроков хранения продукции', 14, date '2026-08-20',
  'Таблица действительна, при условии что не поменялась партия продукта. ВСЕГДА СМОТРИТЕ УПАКОВКУ!');
insert into shelf_life_zone(code, label, temp_text, sort_order) values
 ('ROOM',    'Комнатная температура', '+10…+27 °C', 1),
 ('COLD',    'Холодильная зона',      '+1…+4 °C',   2),
 ('FREEZER', 'Морозильная зона',      '-18…-23 °C', 3),
 ('WATER',   'Вода для мытья',        '+20…+25 °C', 4);

insert into shelf_life_section(title, note, sort_order) values ('ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ', 'Спишите всю продукцию на заправочном столе к закрытию системы. Пополняйте продукты, учитывая использование.', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Салат "Мультименю"', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Салат "Мультименю"'), 'SHELF', 'Вскрытый слив, завернутый в пищевую пленку, в холодильном оборудовании при температуре +1…+4 °C', '24 часа (1 день)', 1440, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Салат "Мультименю"'), 'SHELF', 'В бадейке под заправочным столом в холодильном оборудовании при температуре +1…+4 °C', '6 часов', 360, 'COLD', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Салат "Мультименю"'), 'SHELF', 'На заправочном столе при комнатной температуре +10…+27 °C', '2 часа', 120, 'ROOM', 3);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Лук "Мультименю"', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Лук "Мультименю"'), 'SHELF', 'Вскрытый слив, завернутый в пищевую пленку, в холодильном оборудовании при температуре +1…+4 °C', '18 часов', 1080, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Лук "Мультименю"'), 'SHELF', 'В бадейке в холодильном оборудовании при температуре +1…+4 °C', '6 часов', 360, 'COLD', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Лук "Мультименю"'), 'SHELF', 'На заправочном столе при комнатной температуре +10…+27 °C', '2 часа', 120, 'ROOM', 3);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Сыр чеддер "Hochland"', 3);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Сыр чеддер "Hochland"'), 'SHELF', 'Закрытая упаковка при комнатной температуре +10…+27 °C', '3 часа', 180, 'ROOM', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Сыр чеддер "Hochland"'), 'SHELF', 'Вскрытая, завернутая в пищевую пленку без фирменной упаковки при комнатной температуре +10…+27 °C', '1 час (не включая время выдержки)', 60, 'ROOM', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Сыр чеддер "Hochland"'), 'HOLD', 'Время выдержки при комнатной температуре +10…+27 °C', '1 час', 60, 'ROOM', 3);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Сыр чеддер "Hochland"'), 'SHELF', 'На заправочном столе при комнатной температуре +10…+27 °C', '2 часа (не включая время выдержки)', 120, 'ROOM', 4);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Сыр эмменталь "Hochland"', 4);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Сыр эмменталь "Hochland"'), 'SHELF', 'Закрытая упаковка при комнатной температуре +10…+27 °C', '3 часа', 180, 'ROOM', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Сыр эмменталь "Hochland"'), 'SHELF', 'Вскрытая, завернутая в пищевую пленку без фирменной упаковки при комнатной температуре +10…+27 °C', '1 час (не включая время выдержки)', 60, 'ROOM', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Сыр эмменталь "Hochland"'), 'HOLD', 'Время выдержки при комнатной температуре +10…+27 °C', '1 час', 60, 'ROOM', 3);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Сыр эмменталь "Hochland"'), 'SHELF', 'На заправочном столе при комнатной температуре +10…+27 °C', '2 часа (не включая время выдержки)', 120, 'ROOM', 4);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Томаты целые "Мультименю"', 5);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Томаты целые "Мультименю"'), 'WASH', 'Время мытья в солевом растворе при температуре воды +20…+25 °C', '10 минут', 10, 'WATER', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Томаты целые "Мультименю"'), 'DRY', 'Время сушки после мытья при комнатной температуре +10…+27 °C', '30 минут', 30, 'ROOM', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Томаты целые "Мультименю"'), 'SHELF', 'После мытья/сушки: срок хранения в холодильном оборудовании при температуре +1…+4 °C', '24 часа (1 день)', 1440, 'COLD', 3);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Томаты нарезанные "Мультименю"', 6);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Томаты нарезанные "Мультименю"'), 'SHELF', 'Время хранения в холодильном оборудовании при температуре +1…+4 °C в плотно-закрытой таре', '6 часов', 360, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Томаты нарезанные "Мультименю"'), 'HOLD', 'Выдержка при комнатной температуре +10…+27 °C перед использованием', '1 час', 60, 'ROOM', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Томаты нарезанные "Мультименю"'), 'SHELF', 'На заправочном столе при температуре +10…+27 °C', '1,5 часа (не включая время выдержки)', 90, 'ROOM', 3);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Помидоры черри "Мультименю"', 7);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Помидоры черри "Мультименю"'), 'WASH', 'Время мытья в солевом растворе при температуре воды +20…+25 °C', '10 минут', 10, 'WATER', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Помидоры черри "Мультименю"'), 'DRY', 'Время сушки после мытья при комнатной температуре +10…+27 °C', '30 минут', 30, 'ROOM', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Помидоры черри "Мультименю"'), 'SHELF', 'После мытья/сушки: срок хранения в холодильном оборудовании при температуре +1…+4 °C', '24 часа (1 день)', 1440, 'COLD', 3);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Салат цезарь (без соуса/курицы/креветок)', 8);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Салат цезарь (без соуса/курицы/креветок)'), 'SHELF', 'В холодильном оборудовании при температуре +1…+4 °C', '6 часов', 360, 'COLD', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Лук восстановленный', 9);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Лук восстановленный'), 'HOLD', 'Время восстановления при температуре +1…+4 °C', '1 час', 60, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Лук восстановленный'), 'SHELF', 'В емкости (ведро) в холодильном оборудовании при температуре +1…+4 °C', '24 часа (1 день)', 1440, 'COLD', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Лук восстановленный'), 'SHELF', 'В шейкере в холодильном оборудовании при температуре +1…+4 °C', '24 часа (1 день)', 1440, 'COLD', 3);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Лук восстановленный'), 'SHELF', 'В шейкере при комнатной температуре +10…+27 °C', '2 часа', 120, 'ROOM', 4);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Приправы для гриля', 10);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Приправы для гриля'), 'SHELF', 'В емкости (дозатор) при комнатной температуре +10…+27 °C', '24 часа (1 день)', 1440, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Огурцы маринованные', 11);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Огурцы маринованные'), 'SHELF', 'В рассоле в холодильном оборудовании при температуре +1…+4 °C', '7 дней', 10080, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Огурцы маринованные'), 'SHELF', 'На заправочном столе без рассола при комнатной температуре +10…+27 °C', '24 часа (1 день)', 1440, 'ROOM', 2);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Кетчуп BULK "Eurasian Foods Corporation"', 12);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Кетчуп BULK "Eurasian Foods Corporation"'), 'SHELF', 'Вскрытая упаковка в холодильном оборудовании при температуре +1…+4 °C', '48 часов (2 дня)', 2880, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Кетчуп BULK "Eurasian Foods Corporation"'), 'SHELF', 'В дозаторе на заправочном столе при комнатной температуре +10…+27 °C', '24 часа (1 день)', 1440, 'ROOM', 2);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Горчица BULK "Eurasian Foods Corporation"', 13);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Горчица BULK "Eurasian Foods Corporation"'), 'SHELF', 'Вскрытая упаковка в холодильном оборудовании при температуре +1…+4 °C', '48 часов (2 дня)', 2880, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Горчица BULK "Eurasian Foods Corporation"'), 'SHELF', 'В дозаторе на заправочном столе при комнатной температуре +10…+27 °C', '24 часа (1 день)', 1440, 'ROOM', 2);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Соус гриль\бургер "Петропродукт-отрадное"', 14);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Соус гриль\бургер "Петропродукт-отрадное"'), 'SHELF', 'Вскрытая упаковка в холодильном оборудовании при температуре +1…+4 °C', '72 часа (3 дня)', 4320, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Соус гриль\бургер "Петропродукт-отрадное"'), 'SHELF', 'В дозаторе на заправочном столе при комнатной температуре +10…+27 °C', '24 часа (1 день)', 1440, 'ROOM', 2);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Соус ранч\цезарь "Eurasian Foods Corporation"', 15);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Соус ранч\цезарь "Eurasian Foods Corporation"'), 'SHELF', 'Вскрытая упаковка в холодильном оборудовании при температуре +1…+4 °C', '48 часов (2 дня)', 2880, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Соус ранч\цезарь "Eurasian Foods Corporation"'), 'SHELF', 'В дозаторе на заправочном столе при комнатной температуре +10…+27 °C', '24 часа (1 день)', 1440, 'ROOM', 2);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Трайфл "Лесные ягоды"', 16);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Трайфл "Лесные ягоды"'), 'SHELF', 'В холодильном оборудовании при температуре +1…+4 °C', '72 часа (3 дня, включая время разморозки)', 4320, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Трайфл "Лесные ягоды"'), 'SHELF', 'В зоне Cafe (витрина) в холодильном оборудовании при температуре +1…+4 °C', '48 часов (2 дня, включая время разморозки)', 2880, 'COLD', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Трайфл "Лесные ягоды"'), 'THAW', 'Время разморозки в холодильном оборудовании при температуре +1…+4 °C', '5 часов', 300, 'COLD', 3);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ'), 'Трайфл "Тирамису"', 17);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Трайфл "Тирамису"'), 'SHELF', 'В холодильном оборудовании при температуре +1…+4 °C', '72 часа (3 дня, включая время разморозки)', 4320, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Трайфл "Тирамису"'), 'SHELF', 'В зоне Cafe (витрина) в холодильном оборудовании при температуре +1…+4 °C', '48 часов (2 дня, включая время разморозки)', 2880, 'COLD', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ХОЛОДИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Трайфл "Тирамису"'), 'THAW', 'Время разморозки в холодильном оборудовании при температуре +1…+4 °C', '5 часов', 300, 'COLD', 3);
insert into shelf_life_section(title, note, sort_order) values ('МОРОЗИЛЬНАЯ ПРОДУКЦИЯ', 'Пополнение морозильной (замороженной) продукции строго по актуальной таблице 24/2, количество не должно превышать установленное в ней.', 2);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'МОРОЗИЛЬНАЯ ПРОДУКЦИЯ'), 'Тортилья', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'МОРОЗИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Тортилья'), 'SHELF', 'Срок хранения при комнатной температуре +10…+27 °C', '60 часов (2,5 дня, включая время разморозки)', 3600, 'ROOM', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'МОРОЗИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Тортилья'), 'THAW', 'Время разморозки при комнатной температуре +10…+27 °C', '24 часа', 1440, 'ROOM', 2);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'МОРОЗИЛЬНАЯ ПРОДУКЦИЯ'), 'Булочки', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'МОРОЗИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Булочки'), 'SHELF', 'Срок хранения при комнатной температуре +10…+27 °C', '48 часов (2 дня, включая время разморозки)', 2880, 'ROOM', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'МОРОЗИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Булочки'), 'THAW', 'Время разморозки на стеллаже', '4 часа', 240, null, 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'МОРОЗИЛЬНАЯ ПРОДУКЦИЯ' and p.name = 'Булочки'), 'THAW', 'Время разморозки в стопке (стопка из 8 лотков)', '10-12 часов', 720, null, 3);
insert into shelf_life_section(title, note, sort_order) values ('ОСНОВНОЙ ПРИЛАВОК', null, 3);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Кофе', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Кофе'), 'SHELF', 'Открытый слив, завернутый в пищевую пленку, при комнатной температуре +10…+27 °C', '14 дней', 20160, 'ROOM', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Кофе'), 'SHELF', 'В бункере кофемашины при комнатной температуре +10…+27 °C', '24 часа', 1440, 'ROOM', 2);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Молоко', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Молоко'), 'SHELF', 'В кофемашине в холодильном оборудовании при температуре +1…+4 °C', '24 часа', 1440, 'COLD', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Крошка орео', 3);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Крошка орео'), 'SHELF', 'В дозаторе / в открытом сливе, завернутом в пищевую пленку, при комнатной температуре +10…+27 °C', '72 часа (3 дня)', 4320, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Смеси коктейль и мороженое', 4);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Смеси коктейль и мороженое'), 'SHELF', 'Открытый слив в холодильном оборудовании при температуре +1…+4 °C', '24 часа', 1440, 'COLD', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Сироп клубничный "Аграна Фуд"', 5);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Сироп клубничный "Аграна Фуд"'), 'SHELF', 'В танке комбо-машины при комнатной температуре +10…+27 °C', '7 дней', 10080, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Сироп шоколадный "Аграна Фуд"', 6);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Сироп шоколадный "Аграна Фуд"'), 'SHELF', 'В танке комбо-машины при комнатной температуре +10…+27 °C', '7 дней', 10080, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Сироп ванильный "Аграна Фуд"', 7);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Сироп ванильный "Аграна Фуд"'), 'SHELF', 'В танке комбо-машины при комнатной температуре +10…+27 °C', '7 дней', 10080, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Топпинги комбо', 8);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Топпинги комбо'), 'SHELF', 'В комбо-машине при комнатной температуре +10…+27 °C', '7 дней', 10080, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Сиропы Monin', 9);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Сиропы Monin'), 'SHELF', 'Вскрытая бутылка при комнатной температуре +10…+27 °C', 'Смотреть на бутылке', null, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Сиропы Tastecraft', 10);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Сиропы Tastecraft'), 'SHELF', 'Вскрытая бутылка при комнатной температуре +10…+27 °C', 'Смотреть на бутылке', null, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Сиропы Watson Says', 11);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Сиропы Watson Says'), 'SHELF', 'Вскрытая бутылка при комнатной температуре +10…+27 °C', 'Смотреть на бутылке', null, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Сиропы Gourmix', 12);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Сиропы Gourmix'), 'SHELF', 'Вскрытая бутылка при комнатной температуре +10…+27 °C', 'Смотреть на бутылке', null, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Сиропы для газированных напитков / Fuse tea', 13);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Сиропы для газированных напитков / Fuse tea'), 'SHELF', 'В холодильном оборудовании при температуре +1…+4 °C', '75 дней', 108000, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Сиропы для газированных напитков / Fuse tea'), 'SHELF', 'В аппарате мультиплекс', '60 дней', 86400, null, 2);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Рожки', 14);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Рожки'), 'SHELF', 'На этаже в бадейке при комнатной температуре +10…+27 °C', '24 часа', 1440, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Соусы порционные (дип) от Eurasian Foods Corporation', 15);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Соусы порционные (дип) от Eurasian Foods Corporation'), 'SHELF', 'Срок хранения при комнатной температуре +10…+27 °C', '120 суток (5 дней), см. на этикетке', null, 'ROOM', 1);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ОСНОВНОЙ ПРИЛАВОК'), 'Соусы порционные (дип) от HEINZ', 16);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ОСНОВНОЙ ПРИЛАВОК' and p.name = 'Соусы порционные (дип) от HEINZ'), 'SHELF', 'Срок хранения при комнатной температуре +10…+27 °C', '120 суток (5 дней), см. на этикетке', null, 'ROOM', 1);
insert into shelf_life_section(title, note, sort_order) values ('ЗОНА CAFE', 'Информация по срокам годности продукции Cafe находится в руководстве Cafe.', 4);
insert into shelf_life_section(title, note, sort_order) values ('ЗАВТРАКИ', null, 5);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ЗАВТРАКИ'), 'Булочка "Английский завтрак"', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Булочка "Английский завтрак"'), 'SHELF', 'Срок хранения при комнатной температуре +10…+27 °C (включая время разморозки)', '48 часов (2 дня)', 2880, 'ROOM', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Булочка "Английский завтрак"'), 'THAW', 'Время разморозки', '18 часов', 1080, null, 2);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ЗАВТРАКИ'), 'Ветчина из мяса птицы "Куриная"', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Ветчина из мяса птицы "Куриная"'), 'SHELF', 'Невскрытая упаковка во фризере при температуре -18…-23 °C', 'Согласно маркировке поставщика: со дня изготовления/упаковывания 180 суток', 259200, 'FREEZER', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Ветчина из мяса птицы "Куриная"'), 'SHELF', 'Невскрытая упаковка в холодильном оборудовании при температуре +1…+4 °C (включая время разморозки)', '168 часов (7 дней)', 10080, 'COLD', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Ветчина из мяса птицы "Куриная"'), 'THAW', 'Время разморозки в холодильном оборудовании при температуре +1…+4 °C', '24 часа (1 день)', 1440, 'COLD', 3);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Ветчина из мяса птицы "Куриная"'), 'SHELF', 'Вскрытая упаковка в холодильном оборудовании при температуре +1…+4 °C (не должна превышать таймера на 7 дней), завернутая в пищевую пленку', '48 часов (2 дня)', 2880, 'COLD', 4);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Ветчина из мяса птицы "Куриная"'), 'SHELF', 'На заправочном столе при комнатной температуре +10…+27 °C', '2 часа', 120, 'ROOM', 5);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ЗАВТРАКИ'), 'Говяжья грудинка "Бекон" (20 шт в упаковке)', 3);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Говяжья грудинка "Бекон" (20 шт в упаковке)'), 'SHELF', 'Вскрытая упаковка на производственной морозильной камере (этажный фризер), плотно завернута в стрейч-плёнку в несколько слоёв (минимум три слоя), при температуре -18…-23 °C', '96 часов', 5760, 'FREEZER', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Говяжья грудинка "Бекон" (20 шт в упаковке)'), 'SHELF', 'В холодильном оборудовании при температуре +1…+4 °C (включая время разморозки)', '72 часа (3 дня)', 4320, 'COLD', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Говяжья грудинка "Бекон" (20 шт в упаковке)'), 'SHELF', 'В холодильном оборудовании при температуре +1…+4 °C, полностью размороженный продукт', '48 часов (2 дня)', 2880, 'COLD', 3);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Говяжья грудинка "Бекон" (20 шт в упаковке)'), 'THAW', 'Время разморозки в холодильном оборудовании при температуре +1…+4 °C', '24 часа (1 день)', 1440, 'COLD', 4);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Говяжья грудинка "Бекон" (20 шт в упаковке)'), 'SHELF', 'На заправочном столе при комнатной температуре +10…+27 °C', '2 часа', 120, 'ROOM', 5);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ЗАВТРАКИ'), 'Яйцо сырое', 4);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Яйцо сырое'), 'SHELF', 'Время хранения сырых немытых яиц в основном холодильном оборудовании при температуре +1…+4 °C', '25 дней', 36000, 'COLD', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Яйцо сырое'), 'SHELF', 'Время хранения мытых продезинфицированных яиц в основном холодильном оборудовании при температуре +1…+4 °C', '36 часов', 2160, 'COLD', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Яйцо сырое'), 'SHELF', 'Время хранения мытых продезинфицированных яиц в большом холодильном оборудовании при температуре +1…+4 °C', '24 часа', 1440, 'COLD', 3);
insert into shelf_life_product(section_id, name, sort_order) values ((select id from shelf_life_section where title = 'ЗАВТРАКИ'), 'Масло сливочное', 5);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Масло сливочное'), 'SHELF', 'Невскрытая упаковка во фризере при температуре -18…-23 °C', '3600 часов (150 дней)', 216000, 'FREEZER', 1);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Масло сливочное'), 'THAW', 'Время разморозки в холодильном оборудовании при температуре +1…+4 °C', '36 часов (1,5 дня)', 2160, 'COLD', 2);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Масло сливочное'), 'SHELF', 'Время хранения при температуре +1…+4 °C (включая время разморозки)', '2160 часов (90 дней)', 129600, 'COLD', 3);
insert into shelf_life_rule(product_id, kind, place, term_text, duration_min, zone, sort_order) values ((select p.id from shelf_life_product p join shelf_life_section s on s.id=p.section_id where s.title = 'ЗАВТРАКИ' and p.name = 'Масло сливочное'), 'SHELF', 'Растопленное масло в металлической гастроемкости на грилях', '8 часов (после истечения срока годности должно утилизироваться)', 480, null, 4);